CHANGELOG, src/Ting/Repository/Hydrator.php, src/Ting/Repository/HydratorAggregator.php, tests/units/Ting/Repository/Hydrator.php
Fix: Hydrator IdentityMap can't work since it can't retrieve ref entity
Fix: HydratorAggregator yield one time even when there is 0 result 
| BC breaks?    | "Hydrator::$reference" behavior changes can cause BC break
| Fixed tickets | no
=> Fix Hydrator identityMap

.github/workflows/tests.yml
Setup github actions to run units tests
| BC breaks?    | o
=> Add Github Action which runs Atoum tests

CHANGELOG, src/Ting/Repository/Metadata.php, tests/fixtures/FakeDriver/Driver.php, tests/units/Ting/Repository/Metadata.php
=> Fix: query generator use proper values

CHANGELOG, src/Ting/Repository/Hydrator.php, tests/units/Ting/Repository/Hydrator.php
=> Fix Hydrator fromReference behavior

bitbucket-pipelines.yml
=> remove Bitbucket specific files

src/Ting/Driver/Mysqli/Result.php
=> Replace gettype() by is_string()

sample/src/main.php, sample/src/model/CityRepository.php, src/Ting/Query/Cached/Query.php, src/Ting/Repository/MetadataCacheGenerator.php, src/Ting/Repository/MetadataInitializer.php, tests/fixtures/model/NoMetadataRepository.php, tests/units/Ting/Driver/SphinxQL/Driver.php, tests/units/Ting/Query/Cached/PreparedQuery.php, tests/units/Ting/Query/Generator.php, tests/units/Ting/Repository/Collection.php, tests/units/Ting/Repository/CollectionFactory.php
=> Remove unused imports

src/Ting/Driver/CacheResult.php, src/Ting/Driver/Mysqli/Result.php, src/Ting/Driver/Pgsql/Result.php, src/Ting/Repository/Collection.php, src/Ting/Repository/Hydrator.php, src/Ting/Repository/HydratorAggregator.php, src/Ting/Repository/HydratorArray.php, src/Ting/Repository/HydratorRelational.php, src/Ting/Repository/HydratorSingleObject.php, tests/fixtures/FakeDriver/MysqliResult.php
=> Fix return type deprecations for PHP 8.1

src/Ting/Query/Generator.php, tests/units/Ting/Query/Generator.php
This is a alternative to https://github.com/ccmbenchmark/ting/pull/46 without BC break
=> Add query order & limit

CHANGELOG
=> update CHANGELOG prior release of 3.6.0

src/Ting/Driver/ResultInterface.php, src/Ting/Repository/Collection.php, src/Ting/Repository/CollectionFactory.php, src/Ting/Repository/CollectionFactoryInterface.php, src/Ting/Repository/CollectionInterface.php, src/Ting/Repository/Hydrator.php, src/Ting/Repository/HydratorAggregator.php, src/Ting/Repository/HydratorArray.php, src/Ting/Repository/HydratorInterface.php, src/Ting/Repository/HydratorRelational.php, src/Ting/Repository/Repository.php
=> feat(docs): add generics in phpdoc

.github/workflows/tests.yml
=> fix(ci): run tests on ubuntu 20.04 & schedule run once a week

CHANGELOG, src/Ting/MetadataRepository.php, tests/units/Ting/MetadataRepository.php
Follow https://github.com/ccmbenchmark/ting_api_platform/pull/5#discussion_r1168949194
=> feat(metadata): support searching metadata with the class string of an entity

src/Ting/MetadataRepository.php, src/Ting/Query/QueryInterface.php, src/Ting/Repository/Hydrator.php, src/Ting/Repository/HydratorRelational.php, src/Ting/Repository/HydratorSingleObject.php, src/Ting/Repository/Metadata.php, src/Ting/Repository/Repository.php, src/Ting/Repository/RepositoryFactory.php, tests/units/Ting/Repository/HydratorRelational.php
=> fix(hydrator): fix HydratorRelational when no relation has been defined

CHANGELOG, src/Ting/Driver/Pgsql/Driver.php
Avoid leaks of credentials in logs.
=> fix(security): avoid leaks of credentials

CHANGELOG, src/Ting/Driver/Mysqli/Driver.php, src/Ting/Driver/Mysqli/Result.php, src/Ting/Driver/Mysqli/Statement.php, src/Ting/Driver/Pgsql/Result.php, src/Ting/Driver/SphinxQL/Driver.php, src/Ting/Exception.php, src/Ting/MetadataRepository.php, src/Ting/Query/Generator.php, src/Ting/Repository/Hydrator.php, src/Ting/Repository/Repository.php, src/Ting/Serializer/DateTime.php, src/Ting/UnitOfWork.php, src/Ting/Util/Debug.php
=> Use root namespace for native functions when applicable

.github/workflows/tests.yml, composer.json, src/Ting/Driver/Pgsql/Driver.php, tests/fixtures/mock_native_pgsql.php, tests/units/Ting/Driver/Pgsql/Driver.php, tests/units/Ting/Driver/Pgsql/Result.php, tests/units/Ting/Driver/Pgsql/Statement.php
=> Make tests on PHP 8.1 happy

NEED_TO_BE_DONE_FOR_VERSION_4.md, src/Ting/Driver/DriverInterface.php, src/Ting/Driver/Mysqli/Driver.php, src/Ting/Driver/Pgsql/Driver.php, src/Ting/Query/Query.php, src/Ting/Query/QueryInterface.php, src/Ting/Repository/Metadata.php, tests/fixtures/FakeDriver/Driver.php, tests/units/Ting/Driver/Mysqli/Driver.php, tests/units/Ting/Driver/Pgsql/Driver.php, tests/units/Ting/Query/Query.php, tests/units/Ting/Repository/Metadata.php, tests/units/Ting/UnitOfWork.php
rename method getInsertId into getInsertedId
rename method getInsertIdForSequence in getInsertedIdForSequence
| New feature?  |no
=> feat: rename methods

CHANGELOG, NEED_TO_BE_DONE_FOR_VERSION_4.md, src/Ting/ConnectionPoolInterface.php
=> feat: add setDatabaseOptions on ConnectionPoolInterface

CHANGELOG, src/Ting/Driver/DriverInterface.php, src/Ting/Driver/Mysqli/Driver.php, src/Ting/Driver/Pgsql/Driver.php, src/Ting/Query/Query.php, src/Ting/Query/QueryInterface.php, tests/fixtures/FakeDriver/Driver.php, tests/units/Ting/Driver/Mysqli/Driver.php, tests/units/Ting/Driver/Pgsql/Driver.php, tests/units/Ting/Query/Query.php
=> feat: depreciation getInsertId() and getInsertIdForSequence()

NEED_TO_BE_DONE_FOR_VERSION_4.md, src/Ting/Driver/DriverInterface.php
=> feat: add method setTimezone in DriverInterface

CHANGELOG, composer.json, src/Ting/Driver/Mysqli/Driver.php, src/Ting/Driver/Mysqli/Result.php, tests/units/Ting/Driver/Mysqli/Result.php
=> feat(driver): Add geometry type into MySQL driver

CHANGELOG, src/Ting/Repository/Metadata.php, src/Ting/Repository/Repository.php
| Deprecations? |no
This supersedes #81
=> feat: add support of order and limit in repository

src/Ting/Repository/Hydrator.php, src/Ting/Repository/HydratorAggregator.php, src/Ting/Repository/HydratorRelational.php, src/Ting/Repository/HydratorSingleObject.php, src/Ting/UnitOfWork.php, tests/units/Ting/Repository/Hydrator.php, tests/units/Ting/UnitOfWork.php
=> Refacto: use Weakmap for UnitOfWork internal storage instead of uid indexed arrays

CHANGELOG, composer.json
This dependency is not a hard dep, it should been moved to suggests.
=> [Feature] Remove pimple and move it to suggest

CHANGELOG, composer.json, src/Ting/Repository/Metadata.php, src/Ting/Serializer/DateTimeZone.php, src/Ting/Serializer/Uuid.php, tests/units/Ting/Serializer/DateTimeZone.php, tests/units/Ting/Serializer/Uuid.php
=> Feature: Serializer for dateTimeZone and Uuid

src/Ting/Driver/DriverInterface.php, src/Ting/Driver/Mysqli/Driver.php, src/Ting/Driver/Pgsql/Driver.php, src/Ting/Query/QueryInterface.php, tests/fixtures/FakeDriver/Driver.php
Removes old methods with typos and deprecated in v3
=> chore: removing deprecated methods

CHANGELOG, src/Ting/Repository/Hydrator.php, tests/fixtures/model/CityWithPublicProperties.php, tests/fixtures/model/CityWithPublicPropertiesRepository.php, tests/fixtures/model/CountryWithPublicProperties.php, tests/fixtures/model/CountryWithPublicPropertiesRepository.php, tests/units/Ting/MetadataRepository.php, tests/units/Ting/Repository/HydratorRelational.php
=> Fix HydratorRelational on null join where primary keys are public properties without default value

CHANGELOG, src/Ting/Repository/HydratorAggregator.php, src/Ting/Repository/Metadata.php, tests/units/Ting/Repository/Metadata.php
=> Feature: remove metadata setter & getter

src/Ting/ConnectionPool.php, src/Ting/ConnectionPoolInterface.php, src/Ting/Driver/DriverInterface.php, src/Ting/Driver/Mysqli/Driver.php, src/Ting/Driver/Mysqli/Serializer/Boolean.php, src/Ting/Driver/Pgsql/Driver.php, src/Ting/Driver/Pgsql/Serializer/Boolean.php, src/Ting/Serializer/DateTime.php, src/Ting/Serializer/DateTimeZone.php, src/Ting/Serializer/Ip.php, src/Ting/Serializer/Json.php, src/Ting/Serializer/SerializeInterface.php, src/Ting/Serializer/UnserializeInterface.php, src/Ting/Serializer/Uuid.php, tests/fixtures/FakeDriver/Driver.php
=> feature: typehint serialization interfaces and implementations

CHANGELOG, src/Ting/Driver/Mysqli/Driver.php, tests/fixtures/FakeDriver/Driver.php, tests/fixtures/model/Bouh.php, tests/units/Ting/Driver/Mysqli/Driver.php
| Bug fix?      | yees
| Deprecations?  no
| Tests pass?   | TBD
| Fixed tickets | #1234
=> Fix mysqli_ping for PHP >= 8.2

CHANGELOG, src/Ting/Serializer/BackedEnum.php, tests/fixtures/ColorsEnum.php, tests/units/Ting/Serializer/BackedEnum.php
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
| Fixed tickets | #1234
=> Feature: added BackedEnum Serializer

src/Ting/Entity/NotifyProperty.php
=> feature: reduce context when dumping an Ting Entity
