src/Ting/ConnectionPool.php
src/Ting/Driver/Mysqli/Driver.php
src/Ting/Driver/NeverConnectedException.php
src/Ting/Driver/Pgsql/Driver.php
src/Ting/Exceptions/ConfigException.php
src/Ting/Exceptions/ConnectionException.php
src/Ting/Exceptions/DatabaseException.php
src/Ting/Exceptions/DriverException.php
src/Ting/Exceptions/HydratorException.php
src/Ting/Exceptions/IOException.php
src/Ting/Exceptions/RepositoryException.php
src/Ting/Exceptions/StatementException.php
src/Ting/Exceptions/SyntaxException.php
src/Ting/Exceptions/TransactionException.php
src/Ting/Exceptions/TransationException.php
src/Ting/Exceptions/ValueException.php
src/Ting/Repository/HydratorRelational.php
src/Ting/Repository/Metadata.php
src/Ting/Repository/MetadataCacheGenerator.php
src/Ting/Repository/Repository.php
src/Ting/UnitOfWork.php

Adding new exceptions to enhance the catching granularity.
All the new exceptions extend the `CCMBenchmark\Ting\Exception` class, so the existing code should continue working as expected.
In the future, it would be nice to move the already existing exceptions to the new `CCMBenchmark\Ting\Exceptions` namespace. This way, all the exceptions would live in the same folder, which would make the project more clean (but this would also lead to a BC break, doh!).

Enhance exception granularity

---

src/Ting/Cache/Cache.php

Fix:
```
[info] User Deprecated: Method "Doctrine\Common\Cache\Cache::delete()" might add "bool" as a native return type declaration in the future. Do the same in implementation "CCMBenchmark\Ting\Cache\Cache" now to avoid errors or add an explicit @return annotation to suppress this message.
[info] User Deprecated: Method "Doctrine\Common\Cache\Cache::fetch()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "CCMBenchmark\Ting\Cache\Cache" now to avoid errors or add an explicit @return annotation to suppress this message.
[info] User Deprecated: Method …
```

Fix return type-hint deprecations

---

src/Ting/MetadataRepository.php
tests/fixtures/model/AbstractRepository.php
tests/fixtures/model/BouhReadOnlyRepository.php
tests/fixtures/model/Repository.php
tests/units/Ting/MetadataRepository.php

| Fixed tickets | Ø
We might want to make our repositories extend an abstract class to provide some useful methods. In this case, the metadata loading will try to initialize it. Eventually, it will fail because abstract classes are not meant to be used without an implementation.
This PR fixes this behavior by ensuring only the non-abstract classes are initialized.

Fix MetadataRepository::batchLoadMetadata() loading abstract repositories and interfaces

---

src/Ting/Driver/Mysqli/Driver.php
src/Ting/Driver/Mysqli/Statement.php
tests/units/Ting/Driver/Mysqli/Driver.php
tests/units/Ting/Driver/Mysqli/Statement.php

| Fixed tickets | Ø
When executing prepared query on MySQL, the boolean values are currently converted to their string equivalent:
```php
php > var_dump((string) true);
string(1) "1"
php > var_dump((string) false);
string(0) ""
```
Especially for `false`, this leads to an SQL error, because MySQL doesn't expect an empty string for such value.
In this PR, we convert the boolean values to an integer in order to give MySQL 0 (== false) or 1 (== true).
**Important note:** this issue could have been avoided by using the [`mysqli_prepare()`](https://www.php.net/manual/fr/mysqli.prepare.php). Is there a reason for not …

Fix boolean values support in prepared query

---

CHANGELOG
src/Ting/Driver/Mysqli/Driver.php
tests/units/Ting/Driver/Mysqli/Driver.php

Fix: boolean values support in non-prepared query

---

CHANGELOG
src/Ting/Repository/HydratorRelational.php
tests/fixtures/model/Authority.php
tests/fixtures/model/AuthorityRepository.php
tests/fixtures/model/Department.php
tests/fixtures/model/DepartmentRepository.php
tests/fixtures/model/Nursery.php
tests/fixtures/model/NurseryRepository.php
tests/units/Ting/Repository/HydratorRelational.php

`HydratorRelational` remove result from collection when source was fetched : https://github.com/ccmbenchmark/ting/blob/e02367d004745cdbd02ba6f5b2d575b88099d4c0/src/Ting/Repository/HydratorRelational.php#L222
This mean that hydration must be done in a specific order, depending on target and source dependence defined in `$this->config`
This fix order config to hydrate deepest dependencies first, and root entity lastly.

fix(hydratorRelational): sort config from source and target dependencies

---

CHANGELOG
src/Ting/Driver/DriverInterface.php
src/Ting/Driver/Mysqli/Driver.php
src/Ting/Driver/Pgsql/Driver.php
src/Ting/Query/Query.php
src/Ting/Query/QueryInterface.php
src/Ting/Repository/Metadata.php
tests/units/Ting/Repository/Metadata.php
tests/units/Ting/UnitOfWork.php

…base
This avoids deprecation logs generation since method deprecated methods should not be used in internal codebase.

fix: remove remainings calls to deprecated functions in internal codebase

---

CHANGELOG
src/Ting/Driver/Mysqli/Driver.php
tests/units/Ting/Driver/Mysqli/Driver.php

Mysqli/Driver::ping() relies on mysqli::ping() which throws exceptions when connection has gone down. This is the case when connection timeout is reached ("MySQL server has gone away"). I consider this current behavior a bug because this function should try to reconnect and return false on failure.
I've tried to change the report_mode to MYSQLI_REPORT_OFF but exceptions are still thrown.

fix: catch mysqli::ping() exception in order to try to reconnect

---

CHANGELOG
src/Ting/Repository/Collection.php
tests/units/Ting/Repository/Collection.php

Collection can be serialized, offering a better DX when you want to pass your collection to a controller and send it in json.

[Feature] Collection is now JsonSerializable

---

CHANGELOG
src/Ting/Query/Generator.php
tests/units/Ting/Query/Generator.php

Before this pull request, the generator gave the following sql: `SELECT `id`, `population` FROM `table` WHERE name = #name` (with #name being a parameter for the prepared query, later evaluated to `null`).

[Fix] Query Generator now handle null values

---

.github/workflows/tests.yml
CHANGELOG
src/Ting/Serializer/DateTimeImmutable.php
tests/units/Ting/Serializer/DateTimeImmutable.php

As suggested by @xavierleune in https://github.com/ccmbenchmark/ting/pull/82, this PR adds DateTimeImmutable serialization in v3.X instead of waiting for the release of v4.0

feature: Add DateTimeImmutable serialization

---

.github/workflows/tests.yml
CHANGELOG
composer.json
src/Ting/MetadataRepository.php
src/Ting/Repository/Hydrator.php
src/Ting/Repository/HydratorRelational.php
src/Ting/Repository/Metadata.php
src/Ting/Services.php
src/Ting/Util/PropertyAccessor.php
tests/fixtures/model/HookedPropertiesEntity.php
tests/fixtures/model/PublicPropertiesEntity.php
tests/units/Ting/Repository/Metadata.php
tests/units/Ting/Util/PropertyAccessor.php

This pull requests add supports for entities with public properties.
| Deprecations? | yes: `Metadata::getGetter` and `Metadata::getSetter`
Todo:
Properties can have a property hook to notify the UnitOfWork.

[Feature] Support for public properties

---

CHANGELOG
src/Ting/ConnectionPool.php
src/Ting/Driver/DriverInterface.php
src/Ting/Driver/Mysqli/Driver.php
src/Ting/Driver/Mysqli/Statement.php
src/Ting/Driver/Pgsql/Driver.php
src/Ting/Driver/Pgsql/Statement.php
src/Ting/Driver/StatementInterface.php
src/Ting/MetadataRepository.php
src/Ting/Query/Cached/PreparedQuery.php
src/Ting/Query/Cached/Query.php
src/Ting/Query/PreparedQuery.php
src/Ting/Query/Query.php
src/Ting/Query/QueryFactory.php
src/Ting/Query/QueryFactoryInterface.php
src/Ting/Query/QueryInterface.php
src/Ting/Repository/Repository.php
src/Ting/Services.php

Fix for PHP8.4: Implicitly marking parameter %s as nullable is deprecated

---

src/Ting/Repository/RepositoryFactory.php

The current annotations are correct but not complete enough.
Since repositories extend a base class, they can have method that are not in this base class.
The issue with using `Repository<T>` as the return type is that PHPStan cannot see those methods.
For example: https://phpstan.org/r/65389bf5-b00d-4e5d-b993-8c6f274b7545
With this change, PHPStan understands the correct class while still forcing classes to extend `Repository`.
For example: https://phpstan.org/r/d40317b1-1834-407b-9284-ca1e7b0d3325
You can try removing the `@extends Repository<Foo>` or the `extends Repository` to see the correct errors.

Fix typing for factory

---

NEED_TO_BE_DONE_FOR_VERSION_4.md
src/Ting/UnitOfWork.php

| Deprecations? |no
These function are not needed since Weakmap have been introduces in https://github.com/ccmbenchmark/ting/pull/90

chore: remove unused code

---

CHANGELOG
src/Ting/Services.php

pimple/pimple has been moved from required to suggested dependencies in v3.10.0, however the  use of `CCMBenchmark\Ting\Services` will result in an PHP error. This MR throws a proper exception with instruction to explicitly install pimple.
poke @xavierleune

fix: throw exception if pimple is missing

---

CHANGELOG
src/Ting/Driver/Mysqli/Driver.php
src/Ting/Driver/Mysqli/Statement.php
tests/units/Ting/Driver/Mysqli/Statement.php

This kind of prepared query used to throw an error: `SELECT id FROM table WHERE (organization = :org AND user = :user) OR (organization = :org AND user is null)`. The issue came from using the parameter `org` twice, but it was only binded once for the current parsed statement: `SELECT id FROM table WHERE (organization = ? AND user = :user) OR (organization = ? AND user is null)`
PGSQL is not affected, because it used indexed parameters. The same query will be prepared as `SELECT id FROM table WHERE (organization = $1 AND user = :user) OR (organization = $1 AND user is null)`.
BTW I think that the method `__construct` should be removed from the `CCMBenchmark\Ting\Driver\StatementInterface`, as it may be specific per driver, it would allow better type hints / phpdoc on that part.
| Q …

Fix Driver Mysqli: you can now repeat a same parameter in your query

---

CHANGELOG
src/Ting/Driver/Mysqli/Driver.php
src/Ting/Driver/Pgsql/Driver.php
src/Ting/Repository/CollectionInterface.php

When you fork a process in PHP, all objects are copied in the memory for the new process, but references they hold to resources are kept intact.
When you start interacting with the database in a forked context, the underlying mysqli connection is untouched ; so you can get the results coming from another fork.
This pull requests adds a "reconnect" method to the driver, to recreate the underlying connections and happily query your database without further issues !

Driver now supports reconnect, useful in forked processes

---

CHANGELOG
src/Ting/Entity/NotifyProperty.php
tests/units/Ting/Entity/NotifyProperty.php

Avoid serialization of listeners, this would avoid serializing parts of symfony stack.

feature: prevent entity listener serialization

---

CHANGELOG
src/Ting/Repository/MetadataInitializer.php

Avoids the following Phpstan error :
> Method <A repository>::initMetadata() return type with generic class CCMBenchmark\Ting\Repository\Metadata does not specify its types: T

fix: phpstan generic error

---

CHANGELOG
src/Ting/Driver/CacheResult.php
src/Ting/Driver/Mysqli/Result.php
src/Ting/Driver/Pgsql/Result.php

fix: avoid notice on return types for \Iterator implementations
